#! /bin/bash

# run the script like this:
# $ chmod +x ./path/to/top
# $ ./path/to/top 10 ./path/to/log.txt

# here comes your solution
# e.g.
cat log.txt | grep "18/Oct/2006" | cut -d '"' -f4 | grep -v '-' | sort | uniq -c | sort -n -r | head -10 | awk '{printf("%s - %d - %d%s\n", $2, $1, $1 / 28 * 100, "%" )}' > shell.sh
